db_username: "{{ lookup('env', 'DB_USERNAME') | default('admin') }}"
db_password: "{{ lookup('env', 'DB_PASSWORD') | default('dncewu38oQde4') }}"
db_host: "{{ lookup('env', 'DB_HOST') | default('testdbinstance.cab8a84fusu9.ap-northeast-1.rds.amazonaws.com') }}"

