---

#追記分
- name: Install Puma gem
  ansible.builtin.shell: |
    source /etc/profile.d/rbenv.sh
    gem install puma
  args:
    executable: /bin/bash
  tags: puma

- name: Create Puma configuration file
  ansible.builtin.template:
    src: templates/puma.rb.j2
    dest: /var/sample-app/raisetech-live8-sample-app/config/puma.rb
    owner: ec2-user
    group: ec2-user
    mode: '0644'
 #notify:
 #- Restart Puma
  tags: puma

- name: Create Puma systemd service file
  ansible.builtin.template:
    src: templates/puma.service.j2
    dest: /etc/systemd/system/puma.service
    owner: ec2-user
    group: ec2-user
    mode: '0644'
  notify:
    - Reload systemd
    - Restart Puma
  tags: puma



#権限の設定タスク追加

- name: Ensure tmp directory exists and has correct permissions
  ansible.builtin.file:
    path: /var/sample-app/raisetech-live8-sample-app/tmp
    state: directory
    mode: '0775'
    owner: ec2-user
    group: ec2-user
  tags: puma

- name: Ensure pids directory exists and has correct permissions
  ansible.builtin.file:
    path: /var/sample-app/raisetech-live8-sample-app/tmp/pids
    state: directory
    mode: '0775'
    owner: ec2-user
    group: ec2-user
  tags: puma


# development.rbの設定タスク追加
- name: Update development.rb with allowed hosts
  ansible.builtin.template:
    src: templates/development.rb.j2
    dest: /var/sample-app/raisetech-live8-sample-app/config/environments/development.rb
    owner: ec2-user
    group: ec2-user
    mode: '0644'
  vars:
    host_name: "ec2-43-207-100-7.ap-northeast-1.compute.amazonaws.com"  # ホスト名をここに指定
  tags: rails


- name: Enable Puma service
  ansible.builtin.systemd:
    name: puma
    enabled: yes
    state: started
  tags: puma


- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  tags: puma

- name: Restart Puma service
  ansible.builtin.systemd:
    name: puma
    state: restarted
  tags: puma
