version: 2.1
orbs:
   python: circleci/python@2.0.3
   aws-cli: circleci/aws-cli@3.1.5

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t lecture13/*.yml

  cfn-execute:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Deploy Network Stack
          command: |
            aws cloudformation deploy \
              --template-file lecture13/lecture13_cfn_network.yml \
              --stack-name MyNetworkStack

      - run:
          name: Deploy EC2 Stack
          command: |
            aws cloudformation deploy \
              --template-file lecture13/lecture13_cfn_ec2.yml \
              --stack-name MyEC2Stack \
              --capabilities CAPABILITY_NAMED_IAM

      - run:
          name: Deploy ALB Stack
          command: |
            aws cloudformation deploy \
              --template-file lecture13/lecture13_ALB.yml \
              --stack-name MyALBStack

      - run:
          name: Deploy RDS Stack
          command: |
            aws cloudformation deploy \
              --template-file lecture13/lecture13_cfn_RDS.yml \
              --stack-name MyRDSStack

      - run:
          name: Deploy S3 Stack
          command: |
            aws cloudformation deploy \
              --template-file lecture13/yaml_S3.yml \
              --stack-name MyS3Stack

  # Ansibleの実行ジョブ
  execute-ansible:
    executor: python/default
    steps:
      - checkout
      # SSHキーの追加（フィンガープリントの設定）
      - add_ssh_keys:
          fingerprints:
            - "SHA256:gQOPoizFS1RyIloUBqB19GphWuByvslPGm6xS2ZJgC0"

      # Ansibleのインストール（apt-get）
      - run:
          name: Install Ansible
          command: |
            sudo apt-get update
            sudo apt-get install -y ansible

      # Ansible Playbookの実行（パスをlecture13/Ansibleに修正）
      - run:
          name: Run Ansible Playbook
          command: |
            ansible-playbook -i lecture/Ansible/inventory lecture/Ansible/playbook.yml -u ec2-user --private-key ~/.ssh/id_rsa

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - cfn-lint
      - cfn-execute:
          requires:
            - cfn-lint
      - execute-ansible:
          requires:
            - cfn-execute

