---
- name: remove the MariaDB
  become_user: root
  yum:
    name: mariadb-*
    state: absent

- name: Import MySQL GPG key
  become_user: root
  shell: rpm --import "https://repo.mysql.com/RPM-GPG-KEY-mysql-2023"
  args:
    creates: /var/lib/mysql/mysql80-community-release-el7-7.noarch.rpm

- name: install the mysql rpm from a remote repo
  become_user: root
  yum:
    name: 'https://repo.mysql.com//mysql80-community-release-el7-7.noarch.rpm'
    state: present

- name: install mysql-community-server
  become_user: root
  yum: 
    name: mysql-community-server
    state: present

- name: install mysql-community-devel
  become_user: root
  yum: 
    name: mysql-community-devel
    state: present

- name: Start MySQL service
  become_user: root
  service:
    name: mysqld
    state: started

- name: Copy database.yml template
  ansible.builtin.template:
    src: database.yml.j2
    dest: /var/sample-app/raisetech-live8-sample-app/config/database.yml
    owner: ec2-user
    group: ec2-user
    mode: '0644'
  vars:
    db_username: "admin"  # RDSのusername
    db_password: "dncewu38oQde4"  # RDSのパスワード
    db_host: "testdbinstance.cab8a84fusu9.ap-northeast-1.rds.amazonaws.com"  # RDSのエンドポイント







