---
- name: Add MySQL official repository for Amazon Linux 2
  ansible.builtin.yum_repository:
    name: mysql57-community
    description: MySQL 5.7 Community Server
    baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/
    gpgcheck: yes
    enabled: yes
    gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
    state: present

- name: Clear Yum cache
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Ensure MySQL is installed
  ansible.builtin.yum:
    name: mysql-community-server
    state: present

- name: Start MySQL service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Copy database.yml template
  ansible.builtin.template:
    src: database.yml.j2
    dest: /var/sample-app/raisetech-live8-sample-app/config/database.yml
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Create MySQL database
  ansible.builtin.mysql_db:
    name: sample_db
    state: present
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    login_host: "{{ db_host }}"

- name: Create MySQL user and grant privileges
  ansible.builtin.mysql_user:
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    priv: "sample_db.*:ALL"
    host: "%"
    state: present
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    login_host: "{{ db_host }}"





