---

- name: remove the MariaDB
  become: yes
  yum:
    name: mariadb-*
    state: absent

- name: Import MySQL GPG key
  become: yes
  shell: rpm --import "https://repo.mysql.com/RPM-GPG-KEY-mysql-2023"
  args:
    creates: /var/lib/mysql/mysql80-community-release-el7-7.noarch.rpm

- name: install the mysql rpm from a remote repo
  become: yes
  yum:
    name: 'https://repo.mysql.com//mysql80-community-release-el7-7.noarch.rpm'
    state: present

- name: install mysql-community-server
  become: yes
  yum: 
    name: mysql-community-server
    state: present

- name: install mysql-community-devel
  become: yes
  yum: 
    name: mysql-community-devel
    state: present

- name: Ensure MySQL client libraries are installed
  become: yes
  yum:
    name: mysql-community-libs
    state: present

- name: Set MySQL library path
  become: yes
  lineinfile:
    path: /etc/environment
    line: 'LD_LIBRARY_PATH=/usr/lib64/mysql:$LD_LIBRARY_PATH'
    create: yes

- name: Run ldconfig to update library paths
  become: yes
  command: ldconfig

# 追記分
- name: Ensure rbenv directory has correct permissions
  ansible.builtin.file:
    path: /usr/local/rbenv/versions/3.2.3
    state: directory
    owner: ec2-user  # 必要に応じて変更
    group: ec2-user  # 必要に応じて変更
    mode: '0755'
    recurse: yes
  become: yes

  
# become: yes追記
- name: Install mysql2 gem with bundler
  become: yes
  become_user: ec2-user
  shell: |
    export PATH="/usr/local/rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    bundle config build.mysql2 --with-ldflags=-L/usr/lib64/mysql
    bundle install
  args:
    chdir: /var/sample-app/raisetech-live8-sample-app
    executable: /bin/bash

- name: Start MySQL service
  become: yes
  service:
    name: mysqld
    state: started

- name: Copy database.yml template
  ansible.builtin.template:
    src: database.yml.j2
    dest: /var/sample-app/raisetech-live8-sample-app/config/database.yml
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Ensure log directory exists and has correct permissions
  file:
    path: /var/sample-app/raisetech-live8-sample-app/log
    state: directory
    owner: ec2-user # 実際に存在するユーザー名に変更
    group: ec2-user # 実際に存在するグループ名に変更
    mode: '0755'

- name: Ensure development.log exists and has correct permissions
  file:
    path: /var/sample-app/raisetech-live8-sample-app/log/development.log
    state: touch
    owner: ec2-user # 実際に存在するユーザー名に変更
    group: ec2-user # 実際に存在するグループ名に変更
    mode: '0664'

- name: Ensure db/schema.rb exists and has correct permissions
  file:
    path: /var/sample-app/raisetech-live8-sample-app/db/schema.rb
    state: touch
    owner: ec2-user # 実際に存在するユーザー名に変更
    group: ec2-user # 実際に存在するグループ名に変更
    mode: '0664'



- name: Run db:create to setup the database
  become: yes
  become_user: ec2-user
  shell: |
    export PATH="/usr/local/rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    bin/rails db:create
  args:
    chdir: /var/sample-app/raisetech-live8-sample-app
    executable: /bin/bash

    
- name: Run db:migrate to apply pending migrations
  become: yes
  become_user: ec2-user
  shell: |
    export PATH="/usr/local/rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    bin/rails db:migrate
  args:
    chdir: /var/sample-app/raisetech-live8-sample-app
    executable: /bin/bash


    
