  vars:
    db_username: "admin"  # RDSのusername
    db_password: "dncewu38oQde4"  # RDSのパスワード
    db_host: "testdbinstance.cab8a84fusu9.ap-northeast-1.rds.amazonaws.com"  # RDSのエンドポイント






---

- name: Install MySQL client libraries
  become: yes
  ansible.builtin.yum:
    name: mysql-devel  # CentOS/RHELの場合
    state: present

- name: Copy database.yml template
  ansible.builtin.template:
    src: database.yml.j2
    dest: /var/sample-app/raisetech-live8-sample-app/config/database.yml
    owner: ec2-user
    group: ec2-user
    mode: '0644'



- name: Ensure MySQL is installed
  become: yes
  ansible.builtin.yum:
    name: mysql-server
    state: present

- name: Start MySQL service
  become: yes
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Create MySQL database
  become: yes
  ansible.builtin.mysql_db:
    name: sample_db  # 作成するデータベース名
    state: present
    login_user: "{{ db_username }}"  # MySQLのユーザー名
    login_password: "{{ db_password }}"  # MySQLのパスワード
    login_host: "{{ db_host }}"  # MySQLのホスト

- name: Create MySQL user and grant privileges
  become: yes
  ansible.builtin.mysql_user:
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    priv: "sample_db.*:ALL"
    host: "%"
    state: present
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    login_host: "{{ db_host }}"
    
  vars:
    db_username: "admin"  # RDSのusername
    db_password: "dncewu38oQde4"  # RDSのパスワード
    db_host: "testdbinstance.cab8a84fusu9.ap-northeast-1.rds.amazonaws.com"  # RDSのエンドポイント

