---
- name: MySQL and database setup
  hosts: all
  become: yes

 

  tasks:
    - name: Install MySQL client libraries
      ansible.builtin.yum:
        name: mysql-devel  # CentOS/RHELの場合
        state: present

    - name: Copy database.yml template
      ansible.builtin.template:
        src: database.yml.j2
        dest: /var/sample-app/raisetech-live8-sample-app/config/database.yml
        owner: ec2-user
        group: ec2-user
        mode: '0644'

   vars:
    db_username: "admin"  # RDSのusername
    db_password: "dncewu38oQde4"  # RDSのパスワード
    db_host: "testdbinstance.cab8a84fusu9.ap-northeast-1.rds.amazonaws.com"  # RDSのエンドポイント




