---

- name: remove the MariaDB
  become_user: root
  yum:
    name: mariadb-*
    state: absent

- name: Import MySQL GPG key
  become_user: root
  shell: rpm --import "https://repo.mysql.com/RPM-GPG-KEY-mysql-2023"
  args:
    creates: /var/lib/mysql/mysql80-community-release-el7-7.noarch.rpm

- name: install the mysql rpm from a remote repo
  become_user: root
  yum:
    name: 'https://repo.mysql.com//mysql80-community-release-el7-7.noarch.rpm'
    state: present

- name: install mysql-community-server
  become_user: root
  yum: 
    name: mysql-community-server
    state: present

- name: install mysql-community-devel
  become_user: root
  yum: 
    name: mysql-community-devel
    state: present

- name: Ensure MySQL client libraries are installed
  become_user: root
  yum:
    name: mysql-community-libs
    state: present

- name: Set MySQL library path
  become_user: root
  lineinfile:
    path: /etc/environment
    line: 'LD_LIBRARY_PATH=/usr/lib64/mysql:$LD_LIBRARY_PATH'
    create: yes

- name: Run ldconfig to update library paths
  become_user: root
  command: ldconfig

- name: Install mysql2 gem with bundler
  become: yes  # `ec2-user` で実行する場合は become_user を指定
  become_user: ec2-user
  shell: |
    export PATH="/usr/local/rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    bundle config build.mysql2 --with-ldflags=-L/usr/lib64/mysql
    bundle install
  args:
    chdir: /var/sample-app/raisetech-live8-sample-app
    executable: /bin/bash

- name: Start MySQL service
  become_user: root
  service:
    name: mysqld
    state: started

- name: Copy database.yml template
  ansible.builtin.template:
    src: database.yml.j2
    dest: /var/sample-app/raisetech-live8-sample-app/config/database.yml
    owner: ec2-user
    group: ec2-user
    mode: '0644'

    
