AWSTemplateFormatVersion: 2010-09-09
Description: S3 Template

Resources:
  testS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lecture13
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled
