---
- name: Set Up TargetNode
  hosts: all
  become: yes
  vars:
    app_name: raisetech-live8-sample-app  # 適宜変更
    app_path: /var/sample-app/raisetech-live8-sample-app  # 適宜変更
    ruby_version: 3.2.3  # 2024/10/7現在
    bundler_version: 2.5.19  # 2024/10/7現在
    rails_version: 7.1.3.2  # 2024/10/7現在
    domain: 43.207.100.7  # 適宜変更
    puma_max_threads: 5
    puma_min_threads: 5
    rails_env: development

    # Ansibleのplaybook内でDB_USERNAMEやDB_PASSWORD、DB_HOSTが未定義になって別途、環境変数を定義する必要がある。
    DB_USERNAME: "{{ lookup('env', 'DB_USERNAME') }}"
    DB_PASSWORD: "{{ lookup('env', 'DB_PASSWORD') }}"
    DB_HOST: "{{ lookup('env', 'DB_HOST') }}"

    # aws_region: "{{ lookup('env', 'AWS_REGION') | default('ap-northeast-1', true) }}" # 適宜変更
    # s3_bucket_name: "{{ lookup('env', 'S3_BUCKET_NAME') | default('lecture13', true) }}"  # 適宜変更
    
  tasks:
    - name: Install Git
      ansible.builtin.yum:
        name: git
        state: present
        lock_timeout: 180

  roles:
    - ruby
    - mysql
    - rails_app
    - nginx
    - puma
    - S3

  handlers:
    - name: Reset failed Puma service
      ansible.builtin.command:
        cmd: systemctl reset-failed puma.service
      ignore_errors: true  # リセットが失敗しても続行する

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

