---
- name: Set Up TargetNode
  hosts: all
  become: yes
  vars:
    app_name: raisetech-live8-sample-app
    app_path: /var/sample-app/raisetech-live8-sample-app
    ruby_version: 3.2.3
    domain:  52.196.170.136   # サーバーのIPアドレスまたはドメイン名を指定
    puma_max_threads: 5
    puma_min_threads: 5
    rails_env: development
    aws_region: "{{ lookup('env', 'AWS_REGION') | default('ap-northeast-1', true) }}"
    s3_bucket_name: "{{ lookup('env', 'S3_BUCKET_NAME') | default('lecture13', true) }}"

  tasks:
    - name: Install Git
      ansible.builtin.yum:
        name: git
        state: present
        lock_timeout: 180

    # Serverspecディレクトリの存在確認
    # - name: Check if Serverspec directory exists
    # ansible.builtin.stat:
    # path: /home/ec2-user/spec/spec/lecture13
    # register: serverspec_dir

          #- name: Fail if Serverspec directory is missing
          # ansible.builtin.fail:
          # msg: "Serverspec directory does not exist at /home/ec2-user/spec/spec/lecture13"
          #when: not serverspec_dir.stat.exists

    # Serverspecのテストを実行するタスク
    #- name: Run Serverspec tests
    # shell: |
    # export TARGET_HOST={{ inventory_hostname }} && cd /home/ec2-user/spec/spec/lecture13 && rake spec
    # args:
    # chdir: /home/ec2-user/spec/spec/lecture13  # Serverspecテストがあるディレクトリに変更
    # register: serverspec_output
    # failed_when: "serverspec_output.rc != 0"

  roles:
    - ruby
    - mysql
    - rails_app
    - nginx
    - puma
    - S3

  handlers:
    - name: Reset failed Puma service
      ansible.builtin.command:
        cmd: systemctl reset-failed puma.service
      ignore_errors: true  # リセットが失敗しても続行する

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
