---
# タスクのみを記述
- name: Ensure storage.yml exists for S3 configuration in development
  ansible.builtin.template:
    src: storage.yml.j2
    dest: /var/sample-app/raisetech-live8-sample-app/config/storage.yml
  vars:
    aws_region: "{{ AWS_DEFAULT_REGION }}"
    s3_bucket_name: "{{ S3_BACKET_NAME }}"
  tags: S3


  

- name: Set Active Storage service to S3 in development environment
  lineinfile:
    path: /var/sample-app/raisetech-live8-sample-app/config/environments/development.rb
    regexp: '^ *config.active_storage.service'
    line: "config.active_storage.service = :amazon"
    backrefs: yes
  tags: S3

     #S3の画像表示に必要な構文

- name: Ensure correct ownership and permissions for application.rb
  ansible.builtin.file:
    path: /var/sample-app/raisetech-live8-sample-app/config/application.rb
    owner: ec2-user
    group: ec2-user
    mode: '0644'
  tags: S3

  
- name: Deploy application.rb from template
  ansible.builtin.template:
    src: application.rb.j2
    dest: /var/sample-app/raisetech-live8-sample-app/config/application.rb
    owner: ec2-user
    group: ec2-user
    mode: '0644'
  tags: S3





- name: Ensure correct ownership and permissions for storage directory
  ansible.builtin.file:
    path: /var/sample-app/raisetech-live8-sample-app/storage
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0775'
    recurse: yes
  tags: S3

# ImageMagickのインストール
- name: Install ImageMagick package
  ansible.builtin.yum:
    name: ImageMagick
    state: present
  tags: S3

# mini_magick gemをGemfileに追加
- name: Ensure mini_magick is added to Gemfile
  lineinfile:
    path: /var/sample-app/raisetech-live8-sample-app/Gemfile
    regexp: '^gem .mini_magick.'
    line: 'gem "mini_magick"'
    insertafter: 'gem .image_processing.'  # 適切な場所に挿入
  tags: S3

# Gemfileが更新されたので、bundle installを実行
- name: Run bundle install
  ansible.builtin.shell: |
    source /etc/profile.d/rbenv.sh
    bundle install
  args:
    chdir: /var/sample-app/raisetech-live8-sample-app
    executable: /bin/bash
  tags: S3


- name: Precompile assets with limited resources
  ansible.builtin.shell: |
    source /etc/profile.d/rbenv.sh
    RAILS_ENV=development bundle exec rails assets:precompile -j 1
  args:
    chdir: /var/sample-app/raisetech-live8-sample-app
    executable: /bin/bash
  async: 1200  # 最大20分待機
  poll: 10     # 10秒ごとに進捗確認
  tags: deploy
